server: "http://locahost"
port: 8080
proxyRoot: "/proxy/root"
path:
  - backend
  - 
    - caption
    - 
      - aaa
      - bbb
    - deepdream
    - styletransfer
  - frontend
  - 
    - caption
    - deepdream
    - styletransfer
